name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: uttom
          POSTGRES_PASSWORD: uttom77
          POSTGRES_DB: uttomdb
        ports:
          - 5432:5432
        volumes:
          - pgdata:/var/lib/postgresql/data
        options: >-
          --health-cmd "pg_isready -U uttom"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        volumes:
          - rabbitmq_data:/var/lib/rabbitmq

      minio:
        image: minio/minio
        ports:
          - 9000:9000
          - 9090:9090
        env:
          MINIO_ROOT_USER: "minioadmin"
          MINIO_ROOT_PASSWORD: "minioadmin"
        volumes:
          - minio_data:/data
        command: server /data --console-address ":9090"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Uttom.sln

      - name: Build the solution
        run: dotnet build Uttom.sln --configuration Release --no-restore

      - name: Run Integration Tests
        run: dotnet test Uttom.IntegrationTests/Uttom.IntegrationTests.csproj --configuration Release --no-build --collect:"XPlat Code Coverage"

      - name: Run Unit Tests
        run: dotnet test Uttom.UnitTests/Uttom.UnitTests.csproj --configuration Release --no-build --collect:"XPlat Code Coverage"

volumes:
  pgdata:
  rabbitmq_data:
  minio_data:

